- name: Install docker
  yum:
        name: docker
        state: present

- name: Start and enable docker
  service:
        name: docker
        state: started
        enabled: yes

- name: Install nginx and mysql
  docker_image:
        name: "nginx"
        state: present
        source: pull
  loop:
        - mysql
        - nginx

- name: Run Docker Container
  docker_container:
        name: 
        image: nginx
        ports:
          - "80:80"
        detach: yes
        restart_policy: always
  when: "'{{ service }}' == 'nginx'"

- name: Run containers
  docker_container:
        name: mysql
        image: mysql
        detach: yes
        restart_policy: always
  when: "'{{ service }}' == 'mysql'"
