




- name: Install required packages
  package:
    name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3
          - python3-pip
    state: present

- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
        creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  package:
        name: docker
        state: present

- name: Start and enable Docker service
  service:
        name: docker
        state: started
        enabled: yes

- name: Install Python Docker SDK
  pip:
        name: docker
        state: present
        executable: pip3
        extra_args: --ignore-installed

- name: Add current user to Docker group
  user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

#- name: Restart Docker to apply changes
  #service:
        #name: docker
        #state: restarted


- name: deploy container
  community.docker.docker_container:
    name: nginx
    image: nginx/nginx:latest

